###
POST https://localhost:8080/api/v1/student
Content-Type: application/json

 [   {

        "name": "alice",
        "email": "alice.otondi@gmail.com",
        "dob": "2001-02-05"

    },
    {

        "name": "mercy",
        "email": "alice.otondi@gmail.com",
        "dob": "1999-02-05"
    },
    {

        "name": "mary",
        "email": "alice.otondi@gmail.com",
        "dob": "2000-03-05"
    }
 ]

